#!/usr/bin/bash
# Grap the artist count
# grab the content of file we may need to push in array
# loop through
# echo out
# $1 -> file name, $2 count
#
function highest() {
    howmany='-10'
    if [ -n "$(echo $1 | grep '^-[0-9]\+$' )" ]; then
        howmany=$1
        shift
    elif [ -n "$(echo $1 | grep '^-')" ]; then
        echo 'usage: higest [-N] filename'
        exit 1
    fi

    filename=$1
    sort -nr $filename | head $howmany
}

highest "$@"



