#!/usr/bin/bash

: '
Task: Write a script that calculates the length of a given string.
 Challenge: Use the length of the string to extract the last 3 characters
'

word=hello
len=${#word}

echo "length of $word: $len"

# challenges

echo "last 3 chars: ${word:(len - 3)}"

