#!/usr/bin/bash

: '
Task: Extract the substring from the 2nd character to the 4th character from the string "abcdef". 
The result should be "bcd".

Challenge: Extract the substring from the end of the string, starting from the 3rd character from the end.
'

word="abcdef"
len=$(echo $word | wc -m)
echo "original: $word"

echo "substr(1, 3): ${word:1:3}"

# Challenges
echo "-3:len: ${word:(len - 4)}"

