#!/usr/bin/bash

: ' 
Task: Given the string "apple banana apple", replace all occurrences of apple with orange.
'

sent="apple banana apple"
echo "original string: $sent"

# Will replace entire string
echo "after replace with 'orange' [all]: ${sent//apple/orange}"

# Will replace first string
echo "after repalce with 'orange' [first]: ${sent/apple/orange}"
