#!/usr/bin/bash
: '
Write a function that implements the Korn shell’s cd old new. cd takes the pathname
of the current directory and tries to find the string old. If it finds it, it substitutes new
and attempts to change to the resulting directory.
'

case "$#" in 
    0|1) builtin cd $1;;
    2  ) newdir=${PWD//$1/$2};
        case $newdir in 
            $PWD) echo "bash: cd: bad substitution" >&2 ; 
                return 1;;
            * ) builtin cd $newdir;
                echo $(ls);;
        esac ;;
    *  ) echo "bash: cd: wrong arg count" &1>&2 ; 
        return 1 ;;
esac 

