#!/bin/bash
: '
Write a function that implements the Korn shell’s cd old new. cd takes the pathname
of the current directory and tries to find the string old. If it finds it, it substitutes new
and attempts to change to the resulting directory.
'

old=${1:?"Missing"}
new=${2:?"Missing"}
newdir=$(${PWD/\/$old\//"/$new/"})
if command $newdir; then
    echo "switched to new dir: $newdir"
else
    echo "$newdir is invalid"
fi

