#!/bin/bash
: '
write a script same as ls -l but that prints the information in more user frieldly
'

function finfo() 
{
    if [ ! -e "$1" ]; then
        echo "File $1 doesn't exits."
        exit 1
    fi

    if [ -d "$1" ]; then
        echo -n "$1 is a directory that you may"

        if [ ! -x "$1" ]; then
            echo "not"
        fi
        echo "serach"
    fi

    if [ -f "$1" ]; then
        echo "$1 is a regular file."
    else 
        echo "$1 is a special type of file"
    fi

    if [ -O "$1" ]; then
        echo "You own the file"
    else 
        echo "you donot own the file"
    fi

    if [ -r "$1" ]; then
        echo "You have read permission"
    fi

    if [ -w "$1" ]; then
        echo "You  have write permission"
    fi

    if [ -x "$1" -a ! -d "$1" ]; then
        echo "File is executable, and you have permission to execute"
    fi

}

for file in "$@"; do
    finfo $file
    echo
done
