#!/usr/bin/bash
: '
Task: Automate the creation of a directory structure where each subdirectory contains a placeholder file.
Example: project/{docs,src,bin} with a README.md in each.
Challenge: Use a for loop to iterate through a list of directories and:
Check if each exists.
If not, create it and log the action.
' 

# check if args exists

function create_dir () {

    parent_dir=$1
    new_dir=$2

    if [ ! -d "$parent_dir/$new_dir" ]; then
        mkdir $parent_dir/$new_dir
        echo "created $parent_dir/$new_dir"
    else 
        echo "$parent_dir/$new_dir dir already exists"
    fi

    if [ ! -f "$parent_dir/$new_dir/README.md" ]; then
        echo "# placeholder for md" > "$parent_dir/$new_dir/README.md"
            echo "$parent_dir/$new_dir/README.md create"
        else
            echo "$parent_dir/$new_dir/README.md already exists"
    fi

}

if (($#>0)); then

    parent_dir=project
    # create a parent dir
    if [ ! -d $parent_dir ]; then
        mkdir $parent_dir
        echo "$parent_dir dir created"
    else 
        echo "$parent_dir dir already exists"
    fi

    for dir in  $@; do
        create_dir $parent_dir $dir
    done
else
    echo "Usage: ./cmkdir dirname [dirname2]"
fi

